name: flutter_code_example
description: "Demo on how to interact with Code"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2



flutter:
  uses-material-design: true




